// Generated by tools/clock_profile.py; do not hand edit.
pub const PROFILE_SHA256: &str = "bf852245517b3c9e5530750c98e224c9983837e9bfdc3ff67ff4aa2e3bc1b60c";
#[cfg(feature = "scmi-clock")]
#[used]
#[unsafe(link_section = ".rp1_clock_profile")]
pub static PROFILE_FINGERPRINT: [u8; 64] = *b"bf852245517b3c9e5530750c98e224c9983837e9bfdc3ff67ff4aa2e3bc1b60c";
pub const MAILBOX_CHANNEL: u32 = 0;
#[derive(Clone, Copy, Debug)]
pub struct ClockPolicy { pub name: &'static str, pub rp1_id: u32,
 pub scmi_id: Option<u32>, pub rate_hz: u32,
 pub boot_required: bool, pub rp1_required: bool }
pub const CLOCKS: &[ClockPolicy] = &[
 ClockPolicy { name: "uart", rp1_id: 15, scmi_id: None, rate_hz: 50000000, boot_required: true, rp1_required: true },
 ClockPolicy { name: "mipi0_cfg", rp1_id: 22, scmi_id: None, rate_hz: 25000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "mipi1_cfg", rp1_id: 23, scmi_id: None, rate_hz: 25000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "uart_apb", rp1_id: 6, scmi_id: Some(0), rate_hz: 100000000, boot_required: true, rp1_required: true },
 ClockPolicy { name: "sys", rp1_id: 12, scmi_id: None, rate_hz: 200000000, boot_required: true, rp1_required: true },
 ClockPolicy { name: "dma", rp1_id: 14, scmi_id: None, rate_hz: 100000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "eth", rp1_id: 16, scmi_id: None, rate_hz: 125000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "eth_tsu", rp1_id: 29, scmi_id: None, rate_hz: 50000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "adc", rp1_id: 30, scmi_id: None, rate_hz: 50000000, boot_required: true, rp1_required: false },
];
