// Generated by tools/clock_profile.py; do not hand edit.
pub const PROFILE_SHA256: &str = "48b58f49fb47dace18a22d24a40a6b1f9853df023f2233e7e23355741a7c67d4";
#[cfg(feature = "scmi-clock")]
#[used]
#[unsafe(link_section = ".rp1_clock_profile")]
pub static PROFILE_FINGERPRINT: [u8; 64] = *b"48b58f49fb47dace18a22d24a40a6b1f9853df023f2233e7e23355741a7c67d4";
pub const MAILBOX_CHANNEL: u32 = 1;
#[derive(Clone, Copy, Debug)]
pub struct ClockPolicy { pub name: &'static str, pub rp1_id: u32,
 pub scmi_id: Option<u32>, pub rate_hz: u32,
 pub boot_required: bool, pub rp1_required: bool }
pub const CLOCKS: &[ClockPolicy] = &[
 ClockPolicy { name: "uart", rp1_id: 15, scmi_id: None, rate_hz: 50000000, boot_required: true, rp1_required: true },
 ClockPolicy { name: "mipi0_cfg", rp1_id: 22, scmi_id: None, rate_hz: 25000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "mipi1_cfg", rp1_id: 23, scmi_id: None, rate_hz: 25000000, boot_required: true, rp1_required: false },
 ClockPolicy { name: "uart_apb", rp1_id: 6, scmi_id: Some(0), rate_hz: 100000000, boot_required: true, rp1_required: true },
];
