[package]
name = "rp1-rt"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = []
pcie-ep-init = []
debug-stack-low = []
debug-snapshot = ["debug-stack-low"]
debug-mailbox-layout = ["debug-stack-low"]
debug-mailbox-layout-v1 = ["debug-mailbox-layout"]
debug-mailbox-init = ["debug-mailbox-layout"]
debug-stub = ["pcie-ep-init", "debug-snapshot", "debug-mailbox-init"]
uart0-rx-irq = []
uart1-local-irq = []
uart2-local-irq = []
uart3-local-irq = []
uart4-local-irq = []
uart5-local-irq = []
pwm0-local-irq = []
spi0-local-irq = []
spi0-local-irq-bank1-passive-scout = []
i2c1-local-irq = []
i2c1-local-irq-bank1-passive-scout = []
timer0-alarm0-irq26-candidate = []
expected-fault-recovery = []

[dependencies]
rp1-abi = { path = "../rp1-abi" }
