[package]
name = "rp1-rt"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = []
pcie-ep-init = []
debug-stack-low = []
debug-snapshot = ["debug-stack-low"]
debug-mailbox-layout = ["debug-stack-low"]
debug-mailbox-layout-v1 = ["debug-mailbox-layout"]
debug-mailbox-layout-v2 = ["debug-mailbox-layout"]
debug-mailbox-init = ["debug-mailbox-layout"]
debug-stub = ["pcie-ep-init", "debug-snapshot", "debug-mailbox-init"]
uart0-rx-irq = []

[dependencies]
rp1-abi = { path = "../rp1-abi" }
