#!/usr/bin/env python3
"""Deterministic policy generation. No hardware access; Python 3.11 stdlib."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tomllib

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT / "profiles/rp1-clock-profile.toml"


def load(path=DEFAULT):
    raw = Path(path).read_bytes()
    p = tomllib.loads(raw.decode())
    if p.get("schema") != 1 or not 0 <= p["mailbox_channel"] < 4:
        raise ValueError("profile schema/channel")
    names, rp1_ids, scmi_ids = set(), set(), []
    for c in p["clock"]:
        if not re.fullmatch(r"[a-z][a-z0-9_]{0,14}", c["name"]):
            raise ValueError("clock name must fit SCMI short name")
        if c["name"] in names or c["rp1_id"] in rp1_ids:
            raise ValueError("duplicate clock name/RP1 ID")
        names.add(c["name"])
        rp1_ids.add(c["rp1_id"])
        if c["mode"] not in ("fixed", "scmi", "private"):
            raise ValueError("unknown clock mode")
        if not 0 < c["rate_hz"] < 2**32:
            raise ValueError("clock rate outside u32 DT clock-frequency")
        if c["mode"] == "scmi":
            if type(c["scmi_id"]) is not int or not 0 <= c["scmi_id"] < 32:
                raise ValueError("SCMI vote bitmap supports IDs 0..31")
            scmi_ids.append(c["scmi_id"])
            # Initial backend is deliberately locked-rate. No speculative PLL writer.
            if c["allowed_rates"] != [c["rate_hz"]]:
                raise ValueError("only one locked rate is currently implemented")
        elif "scmi_id" in c:
            raise ValueError("only SCMI_MANAGED clocks have a Linux SCMI ID")
        for flag in ("boot_required", "rp1_required"):
            if not isinstance(c[flag], bool):
                raise ValueError("owner votes must be bool")
    if sorted(scmi_ids) != list(range(len(scmi_ids))):
        raise ValueError("SCMI IDs must be unique and contiguous from zero")
    if not all(isinstance(x, int) and 0 <= x < 54 for x in p["firmware_pins"]):
        raise ValueError("invalid RP1 pin")
    linux = p["linux"]
    labels = linux["disable_labels"] + [linux["uart1_label"], linux["uart1_pins_label"]] + linux["cfe_labels"]
    if not all(re.fullmatch(r"[a-zA-Z_][a-zA-Z0-9_]*", label) for label in labels):
        raise ValueError("invalid DTS label")
    if len(linux["cfe_labels"]) != len(linux["cfe_clocks"]):
        raise ValueError("CFE profile mapping length")
    for name in [linux["uart1_clock"]] + linux["cfe_clocks"]:
        if not any(c["name"] == name and c["mode"] == "fixed" for c in p["clock"]):
            raise ValueError("initial UART/CFE consumer must use a declared fixed clock")
    p["sha256"] = hashlib.sha256(raw).hexdigest()
    return p


def inventory(profile, binding):
    ids = re.findall(r"^#define\s+(RP1_\w+)\s+(\d+)\s*$", Path(binding).read_text(), re.M)
    values = {n: int(v) for n, v in ids}
    if not values or len(set(values.values())) != len(values):
        raise ValueError("binding inventory empty or non-unique")
    selected = {c["rp1_id"]: c for c in profile["clock"]}
    for c in profile["clock"]:
        if values.get(c["binding"]) != c["rp1_id"]:
            raise ValueError("binding ID mismatch: " + c["name"])
    return [{"binding": n, "rp1_id": v,
             "mode": selected[v]["mode"] if v in selected else "UNCLASSIFIED"}
            for n, v in sorted(values.items(), key=lambda item: item[1])]


def outputs(p):
    sha = p["sha256"]
    rust = ["// Generated by tools/clock_profile.py; do not hand edit.",
            f'pub const PROFILE_SHA256: &str = "{sha}";',
            '#[cfg(feature = "scmi-clock")]', '#[used]',
            '#[unsafe(link_section = ".rp1_clock_profile")]',
            f'pub static PROFILE_FINGERPRINT: [u8; 64] = *b"{sha}";',
            f'pub const MAILBOX_CHANNEL: u32 = {p["mailbox_channel"]};',
            "#[derive(Clone, Copy, Debug)]",
            "pub struct ClockPolicy { pub name: &'static str, pub rp1_id: u32,",
            " pub scmi_id: Option<u32>, pub rate_hz: u32,",
            " pub boot_required: bool, pub rp1_required: bool }",
            "pub const CLOCKS: &[ClockPolicy] = &["]
    dts = ["/* Generated policy definitions; transport placement is separate. */", "/ {",
           "    rp1_clock_profile {", f'        profile-sha256 = "{sha}";', "    };"]
    for c in p["clock"]:
        sid = f'Some({c["scmi_id"]})' if c["mode"] == "scmi" else "None"
        rust.append(' ClockPolicy { name: "%s", rp1_id: %d, scmi_id: %s, rate_hz: %d, boot_required: %s, rp1_required: %s },' %
                    (c["name"], c["rp1_id"], sid, c["rate_hz"],
                     str(c["boot_required"]).lower(), str(c["rp1_required"]).lower()))
        if c["mode"] == "fixed":
            dts += [f'    rp1_fixed_{c["name"]}: rp1-fixed-{c["name"].replace("_", "-")} {{',
                    '        compatible = "fixed-clock";', '        #clock-cells = <0>;',
                    f'        clock-frequency = <{c["rate_hz"]}>;',
                    f'        clock-output-names = "rp1-profile-{c["name"]}";', '    };']
    rust += ["];"]
    dts += ["};", "&rp1_scmi {", '    rp1_scmi_clocks: protocol@14 {',
            '        reg = <0x14>;', '        #clock-cells = <1>;', '    };', '};']
    linux = p["linux"]
    ownership = ["/* Generated initial ownership; other enabled consumers MUST be migrated separately. */"]
    ownership += [f'&{label} {{ status = "disabled"; }};' for label in linux["disable_labels"]]
    ownership += [f'&{linux["uart1_label"]} {{', '    status = "okay";',
                  f'    clocks = <&rp1_fixed_{linux["uart1_clock"]}>;', '    clock-names = "uartclk";',
                  f'    pinctrl-0 = <&{linux["uart1_pins_label"]}>;', '    pinctrl-names = "default";',
                  '    /delete-property/ uart-has-rtscts;', '    /delete-property/ skip-init;',
                  '    /delete-property/ assigned-clocks;', '    /delete-property/ assigned-clock-parents;',
                  '    /delete-property/ assigned-clock-rates;', '};']
    for label, clock in zip(linux["cfe_labels"], linux["cfe_clocks"]):
        ownership += [f'&{label} {{', f'    clocks = <&rp1_fixed_{clock}>;',
                      '    /delete-property/ assigned-clocks;', '    /delete-property/ assigned-clock-parents;',
                      '    /delete-property/ assigned-clock-rates;', '};']
    return {
        ROOT / "crates/rp1-hal/src/clock_profile_generated.rs": "\n".join(rust) + "\n",
        ROOT / "profiles/generated/clocks.dtsi": "\n".join(dts) + "\n",
        ROOT / "profiles/generated/ownership.dtsi": "\n".join(ownership) + "\n",
        ROOT / "profiles/generated/validator.json": json.dumps(p, indent=2, sort_keys=True) + "\n",
        ROOT / "profiles/generated/scmi-clock-ids.json": json.dumps(
            {c["name"]: c["scmi_id"] for c in p["clock"] if c["mode"] == "scmi"}, indent=2) + "\n",
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profile", type=Path, default=DEFAULT)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--binding", type=Path)
    a = ap.parse_args()
    p = load(a.profile)
    if a.binding:
        print(json.dumps(inventory(p, a.binding), indent=2))
    for path, content in outputs(p).items():
        if a.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit("STALE: " + str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print("profile " + p["sha256"] + (" checked" if a.check else " generated"))


if __name__ == "__main__":
    main()
